name: 'Docker build'
description: 'Build docker in workdir'
inputs:
  workdir:
    description: 'Build directory'
    required: true
    default: './'
  docker_name:
    description: 'Name of creation docker image'
    required: true
    default: './'
runs:
  using: "composite"
  steps:
    - name: Generate Docker tags
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          docker.io/vxcontrol/${{ inputs.docker_name }}
        tags: |
          type=semver,pattern={{version}}
        flavor: |
          latest=true

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKER_LOGIN }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Go to working directory
      run: |
        cd ${{ inputs.workdir }}
      shell: bash

    - name: Build and push
      uses: docker/build-push-action@v2
      env:
        DOCKER_BUILDKIT: 1
      with:
#        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
