# More info on config here: https://golangci-lint.run/usage/configuration/
run:
  deadline: 3m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - assets
    - build
    - docs
    - db
    - scripts
    - security
    - web
  skip-files:
    - .*\.gen\.go$
    - .*_gen\.go$

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 2
    min-occurrences: 3
  lll:
    line-length: 120
  gci:
    sections:
      - default # Default section: contains all imports that could not be matched to another section type.
      - standard # Standard section: captures all standard packages.
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    # Default: ""
    local-prefixes: soldr

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - goconst
    - goimports
    - gosimple
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - predeclared
    - sqlclosecheck
    - staticcheck
    - typecheck
    - unused

issues:
  exclude-rules:
    - linters:
        - lll
      # Long go generate comments are excluded
      source: "^//go:generate "
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    # for "public interface + private struct implementation" cases only!
    # can be removed in the development phase
    - (comment on exported (method|function|type|const)|should have( a package)? comment|comment should be of the form)
    # not for the active development - can be removed in the stable phase
    - should have a package comment, unless it's in another file for this package
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Rollback). is not checked
    - should check returned error before deferring
    - declaration of "(ok|err|ctx)" shadows declaration
