version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: vx_mysql
    hostname: mysql.local
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
    - "3306:3306"
    volumes:
    - vx-mysql-data:/var/lib/mysql
    networks:
      - vx-stand
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}

  minio:
    image: rancher/minio-minio:RELEASE.2020-07-13T18-09-56Z
    container_name: vx_minio
    hostname: minio.local
    restart: unless-stopped
    ports:
      - "9000:9000"
    command:
      - server
      - /data
    volumes:
      - vx-minio-data:/data
    networks:
      - vx-stand
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}

  modules:
    image: vxcontrol/soldr-modules
    container_name: vx_modules
    hostname: modules.local
    restart: unless-stopped
    links:
    - minio:minio.local
    - mysql:mysql.local
    networks:
      - vx-stand
    environment:
      DB_HOST: mysql.local
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: http://minio.local:9000
    depends_on:
      minio:
        condition: service_started
      mysql:
        condition: service_started

  vxres:
    image: seuz/vxres
    container_name: vx_res
    hostname: vxres.local
    restart: unless-stopped
    links:
      - minio:minio.local
      - mysql:mysql.local
    networks:
      - vx-stand
    environment:
      DB_HOST: mysql.local
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: http://minio.local:9000
    depends_on:
      minio:
        condition: service_started
      mysql:
        condition: service_started
      vxweb:
        condition: service_started

  vxdbmigrate:
    image: seuz/vxdbmigrate
    container_name: vx_dbmigrate
    hostname: vxdbmigrate.local
    links:
      - minio:minio.local
      - mysql:mysql.local
    networks:
      - vx-stand
    environment:
      DB_HOST: mysql.local
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MYSQL_ROOT_USER: ${DB_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      AGENT_SERVER_DB_NAME: ${AGENT_SERVER_DB_NAME}
      AGENT_SERVER_HOST: ${AGENT_SERVER_HOST}
      AGENT_SERVER_DB_USER: ${AGENT_SERVER_DB_USER}
      AGENT_SERVER_DB_PASS: ${AGENT_SERVER_DB_PASS}
      AGENT_SERVER_MINIO_BUCKET_NAME: ${AGENT_SERVER_MINIO_BUCKET_NAME}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: http://minio.local:9000
    depends_on:
      minio:
        condition: service_started
      mysql:
        condition: service_started

  vxserver:
    image: seuz/vxserver
    container_name: vx_server
    hostname: vxserver.local
    restart: unless-stopped
    links:
      - minio:minio.local
      - mysql:mysql.local
    networks:
      - vx-stand
    expose:
      - 8443/tcp
    environment:
      LISTEN: wss://0.0.0.0:8443
      LOG_DIR: logs
      FILES_LOADER: s3
      DB_HOST: mysql.local
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      AGENT_SERVER_DB_NAME: ${AGENT_SERVER_DB_NAME}
      AGENT_SERVER_DB_USER: ${AGENT_SERVER_DB_USER}
      AGENT_SERVER_DB_PASS: ${AGENT_SERVER_DB_PASS}
      AGENT_SERVER_MINIO_BUCKET_NAME: ${AGENT_SERVER_MINIO_BUCKET_NAME}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: http://minio.local:9000
      CONFIG_LOADER: db
      VALID_LOADER: db
    volumes:
      - vxserver-data:/opt/vxserver/data:rw
      - /var/log/vxcontrol/vxserver:/opt/vxserver/logs:rw
    depends_on:
      modules:
        condition: service_started
      vxdbmigrate:
        condition: service_started

  vxweb:
    image: seuz/vxweb
    container_name: vx_web
    hostname: vxweb.local
    restart: unless-stopped
    links:
      - minio:minio.local
      - mysql:mysql.local
    networks:
      - vx-stand
    environment:
      UI_USE_SSL: ${UI_USE_SSL:-true}
      UI_SERVER_HOST: ${UI_SERVER_HOST}
      UI_SERVER_PORT_HTTPS: ${UI_SERVER_PORT_HTTPS:-443}
      UI_SERVER_PORT_HTTP: ${UI_SERVER_PORT_HTTP:-80}
      DB_HOST: mysql.local
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: http://minio.local:9000
    depends_on:
      minio:
        condition: service_started
      mysql:
        condition: service_started

  vxapi:
    image: seuz/vxapi
    container_name: vx_api
    hostname: vxapi.local
    restart: unless-stopped
    links:
      - minio:minio.local
      - mysql:mysql.local
      - vxweb:vxweb.local
    networks:
      - vx-stand
    expose:
      - 8080/tcp
      - 8443/tcp
      - 9080/tcp
    ports:
      - ${MGMT_IP:-0.0.0.0}:${UI_SERVER_PORT_HTTPS:-443}:8443
      - ${MGMT_IP:-0.0.0.0}:${UI_SERVER_PORT_HTTP:-80}:8080
    volumes:
      - vxapi-server-ssl:/opt/api/crts:rw
      - /var/log/vxcontrol/wxapi:/opt/vxapi/logs:rw
    environment:
      DB_HOST: mysql.local
      MGMT_IP: ${MGMT_IP}
      API_USE_SSL: ${UI_USE_SSL:-true}
      API_SERVER_HOST: ${API_SERVER_HOST:-127.0.0.1}
      API_SERVER_PORT_HTTPS: ${API_SERVER_PORT_HTTPS:-:443}
      API_SERVER_PORT_HTTP: ${API_SERVER_PORT_HTTP:-:80}
      API_STATIC_URL: http://vxweb.local:8080
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      API_SSL_KEY: ssl/server.key
      API_SSL_CRT: ssl/server.crt
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
      MINIO_ENDPOINT: http://minio.local:9000
    depends_on:
      minio:
        condition: service_started
      mysql:
        condition: service_started
      vxweb:
        condition: service_started

  vxagent:
    image: seuz/vxagent
    container_name: vx_agent
    hostname: vxagent.local
    restart: unless-stopped
    networks:
      - vx-stand
    environment:
      CONNECT: "wss://vxserver.local:8443"
    depends_on:
      vxserver:
        condition: service_started

networks:
  vx-stand:
    driver: bridge

volumes:
  vx-mysql-data:
    driver: local
  vx-minio-data:
    driver: local
  vxapi-server-ssl:
    driver: local
  vxserver-data:
    driver: local
