name: VXServer build and push

on: workflow_call

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: server
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: debug
        run: |
          ls -R security
      - name: Docker build vxserver
        uses: ./.github/actions/docker_build
        with:
          workdir: "build/package/server"
          docker_name: "vxserver"
          docker_login: ${{ secrets.DOCKER_LOGIN }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
