name: VXServer build and push

on: workflow_call

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: [ ui_backend, all_environment ]
      - name: Docker build vxapi
        uses: ./.github/actions/docker_build
        with:
          workdir: "build/package/api"
          docker_name: "vxapi"
