name: VXServer build and push

on: workflow_call

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: server
      - uses: actions/download-artifact@v3
        with:
          name: all_environment
      - name: Docker build vxserver
        uses: ./.github/actions/docker_build
        with:
          workdir: "build/package/server"
          docker_name: "vxserver"
