name: VXServer build and push

on: workflow_call

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ui_frontend
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build vxweb
        uses: ./.github/actions/docker_build
        with:
          workdir: "build/package/web"
          docker_name: "vxweb"
          docker_login: ${{ secrets.DOCKER_LOGIN }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
