name: VXServer build and push

on: workflow_call

jobs:
  build_and_push_docker:
    name: Docker Build and Publish
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: agent_linux
      - uses: actions/download-artifact@v3
        with:
          name: agent_osx
      - uses: actions/download-artifact@v3
        with:
          name: agent_windows
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: Checkout
        uses: actions/checkout@v3
      - name: Rename Dockerfile
        run: |
          mv build/package/agent/Dockerfile_cross build/package/agent/Dockerfile
      - name: Docker build vxres
        uses: ./.github/actions/docker_build
        with:
          workdir: "build/package/agent"
          docker_name: "vxres"
          docker_login: ${{ secrets.DOCKER_LOGIN }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
