name: Docker build and push

on: push

jobs:
  test_go:
    name: Docker Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: test_go
        uses: ./.github/workflows/workflow-2.yml