name: Docker build and push

on: push

jobs:
  # PREPARE (GENERATE ALL)
  prepare_build:
    uses: ./.github/workflows/prepare_build.yml
  prepare_build_prod:
    if: ${{ github.ref == 'refs/heads/main' }}
#    environment:
#      name: production
    uses: ./.github/workflows/prepare_build_prod.yml
  # TESTS AND LINTERS
  test_go:
    uses: ./.github/workflows/test-go.yml
    needs: prepare_build
  # BUILD BINARY
  build_ui:
    uses: ./.github/workflows/ui-build.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test_go, prepare_build_prod]
  build_server:
    uses: ./.github/workflows/server-build.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test_go, prepare_build_prod]
  build_agent_linux:
    uses: ./.github/workflows/agent-build-linux.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test_go, prepare_build_prod]
  build_agent_windows:
    uses: ./.github/workflows/agent-build-windows.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ test_go, prepare_build_prod ]
  build_agent_osx:
    uses: ./.github/workflows/agent-build-osx.yml
    needs: [ test_go, prepare_build_prod ]
  # BUILD DOCKER
  build_docker_vxweb:
    uses: ./.github/workflows/build-docker-vxweb.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: production
    needs: build_ui
  build_docker_vxapi:
    uses: ./.github/workflows/build-docker-vxapi.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: production
    needs: build_ui
  build_docker_vxagent:
    uses: ./.github/workflows/build-docker-vxagent.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: production
    needs: build_agent_linux
  build_docker_vxres:
    uses: ./.github/workflows/build-docker-vxagent.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: production
    needs: [ build_agent_linux, build_agent_windows, build_agent_osx ]
  build_docker_vxserver:
    uses: ./.github/workflows/build-docker-vxserver.yml
    if: ${{ github.ref == 'refs/heads/main' }}
    environment:
      name: production
    needs: build_server
