name: Generate build env

on: workflow_call

jobs:
  generate_all:
    name: Generate all
    runs-on: ubuntu-latest
    container:
      image: vxcontrol/vxbuild-cross:1.19.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ALL
        run: |
          chmod +x scripts/gen-certs.sh
          make generate-all
      - name: Upload math result for generate_all
        uses: actions/upload-artifact@v3
        with:
          name: all_environment
          path: |
            build/ssl/*
            security/certs
            security/vconf/hardening/abh.json
            security/vconf/lic/sbh.json
            internal/app/api/utils/dbencryptor/sec-store-key.txt
