name: Generate build env

on: workflow_call

jobs:
  decode_all:
    name: Generate all
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ALL
        run: |
          echo -e "${{secrets.GEN_CERTS}}" > temp.txt
          echo -e "${{secrets.GEN_CERTS_PUB}}" > temp_pub.txt
          echo 1111 > temp3.txt
          chmod +x decode_cert.sh
          ./decode_cert.sh
#          rm temp.txt
#          echo -n "$CERTS" | base64 --decode > certs.tar.gz
#          tar -xvf certs.tar.gz
      - name: Upload result for generate_all
        uses: actions/upload-artifact@v3
        with:
          name: decode_environment
          path: |
            temp.txt
            temp_pub.txt
            temp3.txt
            build/ssl/*
            security/certs
            security/vconf/hardening/abh.json
            security/vconf/lic/sbh.json
            internal/app/api/utils/dbencryptor/sec-store-key.txt
