name: Generate build env

on: workflow_call

jobs:
  decode_all:
    name: Generate all
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ALL
        env:
          CERTS: ${{ secrets.GEN_CERTS }}
        run: |
          echo -n "$CERTS" > temp.txt
          cat temp.txt
#          rm temp.txt
#          echo -n "$CERTS" | base64 --decode > certs.tar.gz
#          tar -xvf certs.tar.gz
      - name: Upload result for generate_all
        uses: actions/upload-artifact@v3
        with:
          name: decode_environment
          path: |
            temp.txt
            build/ssl/*
            security/certs
            security/vconf/hardening/abh.json
            security/vconf/lic/sbh.json
            internal/app/api/utils/dbencryptor/sec-store-key.txt
