name: Generate build env

on: workflow_call

jobs:
  decode_all:
    name: Generate all
    environment:
      name: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate ALL
#        env:
#          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
        run: |
          echo -n "${{secrets.GEN_CERTS}}" > temp.txt
          echo "$CERTIFICATE_BASE64" > temp_pub.txt
          echo 1111 > temp3.txt
          chmod +x decode_cert.sh
          ./decode_cert.sh
#          rm temp.txt
          echo -n "${{secrets.GEN_CERTS}}" | base64 --decode > certs.tar.gz
          echo -n "$CERTIFICATE_BASE64" | base64 --decode > certs2.tar.gz
          tar -tvf certs.tar.gz
          tar -tvf certs2.tar.gz
#          tar -xvf certs.tar.gz
      - name: Upload result for generate_all
        uses: actions/upload-artifact@v3
        with:
          name: decode_environment
          path: |
            temp.txt
            temp_pub.txt
            temp3.txt
            certs.tar.gz
            certs2.tar.gz
            build/ssl/*
            security/certs
            security/vconf/hardening/abh.json
            security/vconf/lic/sbh.json
            internal/app/api/utils/dbencryptor/sec-store-key.txt
