name: Build UI

on: workflow_call

jobs:
  ui_build_backend:
    name: Code lint with golangci-lint
    runs-on: ubuntu-latest
    container:
      image: vxcontrol/vxbuild-cross:1.19.1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Common
        uses: ./.github/workflows/common.yml
      - name: run_golangci-lint
        run: |
          echo "make build-ui"

  ui_build_frontend:
    name: Code test with go test
    runs-on: ubuntu-latest
    container:
      image: node:15

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Common
        uses: ./.github/workflows/common.yml
      - name: run_go-test
        run: |
          echo "cd client && yarn install"
          echo "npx --max_old_space_size=4096 vue-cli-service build"