name: Build UI

on: workflow_call

jobs:
  ui_build_backend:
    name: Build backend UI
    runs-on: ubuntu-latest
    container:
      image: vxcontrol/vxbuild-cross

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Common
        uses: ./.github/actions/common
      - name: Enable cache
        uses: ./.github/actions/go_cache
      - uses: actions/download-artifact@v3
        with:
          name: decode_environment
      - name: Build
        run: |
          make build-api
          echo "./build/bin/vxapi"
          ls -la ./build/bin/vxapi || true
          echo "./build/artifacts/api"
          ls -la ./build/artifacts/api || true
      - name: Upload result for ui_build_backend
        uses: actions/upload-artifact@v3
        with:
          name: ui_backend
          path: |
            ./build/bin/vxapi
            ./cmd/api


  ui_build_frontend:
    name: Build frontend UI
    runs-on: ubuntu-latest
    container:
      image: node:16

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create directories
        uses: ./.github/actions/common
      - name: Enable cache
        uses: ./.github/actions/yarn_cache
      - name: Build
        run: |
          make build-web
      - name: Upload result for ui_build_frontend
        uses: actions/upload-artifact@v3
        with:
          name: ui_frontend
          path: web/dist/
